<a href="https://colab.research.google.com/github/Eizer-GH/PDS/blob/main/Ex4_B4_55_PrasadV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
NAME - Prasad Sanjay Vangujare
CLASS - SY.B [AIDS]
ROLL NO.- B55
SUBJECT - EX_4 PDS
```

```
AIM - Numerical Computation with NumPy: Perform different computations using   
      NumPy library.
```

```
Theory :

Q1. Explain the role of NumPy in the Python scientific computing ecosystem.

NumPy plays a fundamental role in the Python scientific computing ecosystem by
providing a powerful and efficient way to store and manipulate numerical data
using arrays. It introduces the NumPy array, which is faster and more memory-
efficient than traditional Python lists when handling large datasets. NumPy
includes many built-in mathematical and statistical functions that allow users
to perform complex calculations easily and quickly. It also acts as a foundation
for many other scientific libraries such as Pandas, Matplotlib,and Scikit-learn,
making it an essential tool for data analysis, scientificresearch, and machine
learning tasks.


Q2. Why is NumPy considered faster than pure Python computations?

NumPy is considered faster than pure Python computations because it is
implemented using optimized C programming code that runs at a much lower
level than regular Python instructions. It uses a concept called vectorization,
which allows operations to be performed on entire arrays at once instead of
processing elements one by one using loops. This reduces the need for slow
Python loops and improves execution speed significantly. Additionally, NumPy
stores data in continuous memory locations, which improves memory access speed
and overall computational efficiency when working with large numerical data.


Q3. What types of mathematical operations can be performed using NumPy?

NumPy supports a wide variety of mathematical operations that can be applied
directly to arrays and matrices. Basic arithmetic operations such as addition,
subtraction, multiplication, and division can be performed easily between arrays
or between arrays and scalar values. It also provides advanced mathematical
functions including exponentiation, square root, logarithmic functions, and
trigonometric functions like sine, cosine, and tangent.
In addition, NumPy supports statistical operations such as mean, median,
standard deviation, variance, minimum, and maximum calculations.
Matrix operations such as matrix multiplication, transpose, and determinant
calculation can also be performed, making NumPy highly useful for scientific
and engineering applications.


Q4. Explain indexing and slicing in NumPy arrays.

Indexing and slicing in NumPy arrays are methods used to access specific
elements or portions of an array. Indexing refers to selecting a single
element from an array using its position number, where indexing usually
starts from zero just like Python lists. For example, accessing the first
element uses index position zero, while negative indexing can be used to
access elements from the end of the array. Slicing refers to selecting a
group of elements from an array using a range of index values. It allows
users to extract subsets of data without modifying the original array
structure. NumPy also supports multi-dimensional indexing and slicing,
which makes it easy to work with rows, columns, or sections of larger
datasets.


Q5. How does NumPy integrate with libraries like:
a. Pandas
b. Matplotlib
c. Scikit-learn

NumPy integrates closely with many other Python libraries and acts as the
core numerical engine behind them. Pandas uses NumPy arrays as the underlying
structure for storing data inside Series and DataFrame objects, allowing fast
data manipulation and analysis. Matplotlib uses NumPy arrays to create
graphical visualizations such as line plots, bar charts,histograms, and
scatter plots, making it easy to convert numerical data into visual insights.
Scikit-learn relies heavily on NumPy arrays to store datasets and perform
machine learning computations, and most machine learning models accept NumPy
arrays as input for training and prediction tasks.
```


In [ ]:
# Practical 4: Numerical Computation with NumPy

import numpy as np
import time

print("----- Task 1: Create a NumPy array from a list -----")

list_data = [1, 2, 3, 4, 5]
arr = np.array(list_data)

print("List:", list_data)
print("NumPy Array:", arr)



print("\n----- Task 2: Perform basic arithmetic operations -----")

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)



print("\n----- Task 3: Find sum and mean of array -----")

arr2 = np.array([5, 10, 15, 20])

print("Sum:", np.sum(arr2))
print("Mean:", np.mean(arr2))



print("\n----- Task 4: Reshape a one dimensional array -----")

arr3 = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr3.reshape(2, 3)

print("Original Array:", arr3)
print("Reshaped Array:\n", reshaped)



print("\n----- Task 5: Access elements using indexing -----")

arr4 = np.array([100, 200, 300, 400, 500])

print("First Element:", arr4[0])
print("Third Element:", arr4[2])
print("Last Element:", arr4[-1])



print("\n----- Task 6: Matrix addition and multiplication -----")

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

print("Matrix Addition:\n", mat1 + mat2)

print("Matrix Multiplication:\n", np.dot(mat1, mat2))



print("\n----- Task 7: Generate random numbers -----")

random_nums = np.random.rand(5)

print("Random Numbers:", random_nums)



print("\n----- Task 8: Compute standard deviation and variance -----")

arr5 = np.array([2, 4, 6, 8, 10])

print("Standard Deviation:", np.std(arr5))
print("Variance:", np.var(arr5))



print("\n----- Task 9: Use NumPy mathematical functions -----")

arr6 = np.array([1, 4, 9, 16])

print("Square Root:", np.sqrt(arr6))
print("Exponential:", np.exp(arr6))
print("Logarithm:", np.log(arr6))



print("\n----- Task 10: Compare Python list and NumPy array -----")

py_list = [1, 2, 3, 4, 5]

start = time.time()
py_result = [x * 2 for x in py_list]
end = time.time()

print("Python List Result:", py_result)
print("Python Time:", end - start)

np_arr = np.array(py_list)

start = time.time()
np_result = np_arr * 2
end = time.time()

print("NumPy Array Result:", np_result)
print("NumPy Time:", end - start)



print("\n----- Task 11: Vectorized operations -----")

large_arr = np.arange(1000000)

start = time.time()
vector_result = large_arr * 2
end = time.time()

print("Vectorized Operation Time:", end - start)



print("\n----- Task 12: Solve system of linear equations -----")

A = np.array([[2, 1], [5, 3]])
B = np.array([8, 18])

solution = np.linalg.solve(A, B)

print("Solution of equations:", solution)



print("\n----- Task 13: Broadcasting operations -----")

arr7 = np.array([1, 2, 3])
scalar = 5

broadcast_result = arr7 + scalar

print("Broadcasting Result:", broadcast_result)



print("\n----- Task 14: Analyze large dataset -----")

large_data = np.random.randint(1, 100, size=1000)

print("Minimum:", np.min(large_data))
print("Maximum:", np.max(large_data))
print("Average:", np.mean(large_data))



print("\n----- Task 15: Optimize computations using NumPy -----")

data = np.arange(1, 1001)

optimized_result = np.sum(data ** 2)

print("Optimized Computation Result:", optimized_result)



----- Task 1: Create a NumPy array from a list -----
List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]

----- Task 2: Perform basic arithmetic operations -----
Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]

----- Task 3: Find sum and mean of array -----
Sum: 50
Mean: 12.5

----- Task 4: Reshape a one dimensional array -----
Original Array: [1 2 3 4 5 6]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]

----- Task 5: Access elements using indexing -----
First Element: 100
Third Element: 300
Last Element: 500

----- Task 6: Matrix addition and multiplication -----
Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]

----- Task 7: Generate random numbers -----
Random Numbers: [0.55127435 0.24246217 0.19674324 0.26269895 0.89161754]

----- Task 8: Compute standard deviation and variance -----
Standard Deviation: 2.8284271247461903
Variance: 8.0

----- Task 9: Use NumPy mathematical functions -----
Square Root: [1. 2. 3. 4.]
Expo

```
Conclusion -

In this practical, various numerical computations were performed using the
NumPy library, which demonstrated its efficiency and flexibility in handling
numerical data. Different types of arrays were created from Python lists
and used to perform arithmetic operations such as addition, subtraction,
multiplication, and division. Important statistical measures like sum,
mean, standard deviation, and variance were also calculated, which helped
in understanding how NumPy simplifies mathematical analysis on datasets.

The practical also covered reshaping arrays, accessing elements using
indexing, and performing matrix operations such as matrix addition and
multiplication. Advanced features such as vectorized operations,
broadcasting, solving systems of linear equations, and generating random
numbers were explored to highlight the power of NumPy in scientific and
engineering computations. Overall, this practical provided a clear
understanding of how NumPy improves performance and makes numerical
computations faster, simpler, and more efficient when working with both
small and large datasets.
```
